In [1]:
import jax
import jax.numpy as jnp
import numpy as np

/Users/qwe/miniforge3/lib/python3.8/site-packages/jax/_src/lib/__init__.py:32: UserWarning: JAX on Mac ARM machines is experimental and minimally tested. Please see https://github.com/google/jax/issues/5501 in the event of problems.
  warnings.warn("JAX on Mac ARM machines is experimental and minimally tested. "


In [5]:
np.random.seed(1)
N = 20
beta = 1
x = np.random.randint(0,2,size=N)
x= x/ np.linalg.norm(x)
x

array([0.30151134, 0.30151134, 0.        , 0.        , 0.30151134,
       0.30151134, 0.30151134, 0.30151134, 0.30151134, 0.        ,
       0.        , 0.30151134, 0.        , 0.30151134, 0.30151134,
       0.        , 0.        , 0.30151134, 0.        , 0.        ])

In [13]:
sigma_z = jnp.array([[1,0],[0,-1]])
Pr_expm = jnp.expm1(- beta * (jnp.identity(2) - sigma_z)/2)

psa = jnp.stack((sigma_z,)*N,axis=-1)


(2, 2, 20)

DeviceArray([[0., 0.],
             [0., 1.]], dtype=float32)

In [33]:
np.outer(x,x.T) @ x

array([0.30151134, 0.30151134, 0.        , 0.        , 0.30151134,
       0.30151134, 0.30151134, 0.30151134, 0.30151134, 0.        ,
       0.        , 0.30151134, 0.        , 0.30151134, 0.30151134,
       0.        , 0.        , 0.30151134, 0.        , 0.        ])

In [ ]:
np.random( )